# generated by datamodel-codegen:
#   filename:  CaseRelationshipUpdate.schema.json
#   timestamp: 2026-01-20T23:02:24+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Source(Enum):
    orcabus_casemanager = "orcabus.casemanager"


class Action(Enum):
    CREATE = "CREATE"
    DELETE = "DELETE"


class CaseRelationshipUpdate(BaseModel):
    action: Action
    addedVia: str
    case: Dict[str, Any]
    externalEntity: Dict[str, Any]


class CaseRelationshipUpdateEvent(BaseModel):
    id: Optional[str] = None
    region: Optional[str] = None
    resources: Optional[List[str]] = None
    source: Source
    time: Optional[datetime] = None
    version: Optional[str] = None
    account: Optional[str] = None
    detail_type: str = Field(..., alias="detail-type")
    detail: CaseRelationshipUpdate
