# generated by datamodel-codegen:
#   filename:  CaseStateChange.schema.json
#   timestamp: 2026-08-21T05:53:56+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Source(Enum):
    orcabus_casemanager = "orcabus.casemanager"


class DetailType(Enum):
    CaseStateChange = "CaseStateChange"


class Action(Enum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"


class CaseStateChange(BaseModel):
    action: Action
    refId: str = Field(..., description="The orcabus_id of the case")
    timestamp: str
    case: Dict[str, Any]


class CaseStateChangeEvent(BaseModel):
    id: Optional[str] = None
    region: Optional[str] = None
    resources: Optional[List[str]] = None
    source: Source
    time: Optional[datetime] = None
    version: Optional[str] = None
    account: Optional[str] = None
    detail_type: DetailType = Field(..., alias="detail-type")
    detail: CaseStateChange
