# generated by datamodel-codegen:
#   filename:  CaseRelationshipStateChange.schema.json
#   timestamp: 2025-09-09T15:03:10+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Source(Enum):
    orcabus_casemanager = 'orcabus.casemanager'


class DetailType(Enum):
    CaseRelationshipStateChange = 'CaseRelationshipStateChange'


class Action(Enum):
    CREATE = 'CREATE'
    DELETE = 'DELETE'


class CaseRelationshipStateChange(BaseModel):
    action: Action
    refId: str
    addedVia: str
    timestamp: str
    case: Dict[str, Any]
    externalEntity: Dict[str, Any]


class CaseRelationshipStateChangeEvent(BaseModel):
    id: Optional[str] = None
    region: Optional[str] = None
    resources: Optional[List[str]] = None
    source: Source
    time: Optional[datetime] = None
    version: Optional[str] = None
    account: Optional[str] = None
    detail_type: DetailType = Field(..., alias='detail-type')
    detail: CaseRelationshipStateChange
