# generated by datamodel-codegen:
#   filename:  CaseRelationshipStateChange.schema.json
#   timestamp: 2026-08-13T09:00:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field


class Source(Enum):
    orcabus_casemanager = "orcabus.casemanager"


class DetailType(Enum):
    CaseRelationshipStateChange = "CaseRelationshipStateChange"


class Action(Enum):
    CREATE = "CREATE"
    DELETE = "DELETE"


class CaseRelationshipStateChange(BaseModel):
    action: Action
    refId: str
    addedVia: str | None = None
    timestamp: str
    case: dict[str, Any]
    externalEntity: dict[str, Any]


class CaseRelationshipStateChangeEvent(BaseModel):
    id: str | None = None
    region: str | None = None
    resources: list[str] | None = None
    source: Source
    time: AwareDatetime | None = None
    version: str | None = None
    account: str | None = None
    detail_type: DetailType = Field(..., alias="detail-type")
    detail: CaseRelationshipStateChange
