# Generated by Django 5.2 on 2025-06-23 04:45

import case_manager.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "orcabus_id",
                    case_manager.fields.OrcaBusIdField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("case_name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaseState",
            fields=[
                (
                    "orcabus_id",
                    case_manager.fields.OrcaBusIdField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("status", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="case_manager.case",
                    ),
                ),
            ],
            options={
                "unique_together": {("case", "status", "timestamp")},
            },
        ),
    ]
