# Generated by Django 6.0.4 on 2026-04-29 07:48

import app.fields
import app.models.case
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "orcabus_id",
                    app.fields.OrcaBusIdField(primary_key=True, serialize=False),
                ),
                (
                    "request_form_id",
                    models.CharField(
                        help_text="The unique ID from the external request form associated with this case.",
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="A brief description of the case",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("wgts", "WGTS"), ("cttso", "ctTSO")],
                        help_text="The type for this case e.g. WGTS, ctTSO",
                    ),
                ),
                (
                    "study_type",
                    models.CharField(
                        choices=[("clinical", "Clinical"), ("research", "Research")],
                        help_text='Whether this is a "clinical" or "research" case',
                    ),
                ),
                (
                    "is_report_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether a report is required for this case",
                    ),
                ),
                (
                    "is_nata_accredited",
                    models.BooleanField(
                        default=True,
                        help_text="Whether a case is a NATA accredited case",
                    ),
                ),
                (
                    "links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='A dict of named links, e.g. {"trello": "https://...", "drive": "https://..."}',
                        null=True,
                        validators=[app.models.case.validate_urls_dict],
                    ),
                ),
                (
                    "alias",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of aliases for this case, typically populated with external IDs to make searching easier.",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExternalEntity",
            fields=[
                (
                    "orcabus_id",
                    app.fields.OrcaBusIdField(primary_key=True, serialize=False),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        help_text="The prefix in the orcabus_id, indicating the entity's type or source system. Used to distinguish between different entity types or services.",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="The entity type within its service, e.g., 'library', 'subject', or 'sequence'. Typically matches the subpath or resource type in the source service.",
                        null=True,
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the microservice or domain where the entity is managed, e.g., 'metadata', 'workflow', or 'sequence'.",
                        null=True,
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        help_text="A human-friendly identifier for this entity, such as a library ID or workflow run ID, for easier recognition than the orcabus_id.",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalCase",
            fields=[
                ("orcabus_id", app.fields.OrcaBusIdField(db_index=True)),
                (
                    "request_form_id",
                    models.CharField(
                        db_index=True,
                        help_text="The unique ID from the external request form associated with this case.",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="A brief description of the case",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("wgts", "WGTS"), ("cttso", "ctTSO")],
                        help_text="The type for this case e.g. WGTS, ctTSO",
                    ),
                ),
                (
                    "study_type",
                    models.CharField(
                        choices=[("clinical", "Clinical"), ("research", "Research")],
                        help_text='Whether this is a "clinical" or "research" case',
                    ),
                ),
                (
                    "is_report_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether a report is required for this case",
                    ),
                ),
                (
                    "is_nata_accredited",
                    models.BooleanField(
                        default=True,
                        help_text="Whether a case is a NATA accredited case",
                    ),
                ),
                (
                    "links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='A dict of named links, e.g. {"trello": "https://...", "drive": "https://..."}',
                        null=True,
                        validators=[app.models.case.validate_urls_dict],
                    ),
                ),
                (
                    "alias",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of aliases for this case, typically populated with external IDs to make searching easier.",
                        null=True,
                    ),
                ),
                ("history_user_id", models.CharField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical case",
                "verbose_name_plural": "historical cases",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "orcabus_id",
                    app.fields.OrcaBusIdField(primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaseExternalEntityLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        db_column="case_orcabus_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.case",
                    ),
                ),
                (
                    "external_entity",
                    models.ForeignKey(
                        db_column="external_entity_orcabus_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.externalentity",
                    ),
                ),
            ],
            options={
                "unique_together": {("case", "external_entity")},
            },
        ),
        migrations.AddField(
            model_name="case",
            name="external_entity_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="case_set",
                through="app.CaseExternalEntityLink",
                to="app.externalentity",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalCaseExternalEntityLink",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, editable=False)),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_column="case_orcabus_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="app.case",
                    ),
                ),
                (
                    "external_entity",
                    models.ForeignKey(
                        blank=True,
                        db_column="external_entity_orcabus_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="app.externalentity",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.historicalcase",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalCaseExternalEntityLink",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "orcabus_id",
                    app.fields.OrcaBusIdField(primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("request_received", "Request Received"),
                            ("sample_received", "Sample Received"),
                            ("library_partially_failed", "Library Partially Failed"),
                            ("sequencing_started", "Sequencing Started"),
                            ("sequencing_completed", "Sequencing Completed"),
                            ("bioinformatics_started", "Bioinformatics Started"),
                            ("bioinformatics_completed", "Bioinformatics Completed"),
                            ("curation_started", "Curation Started"),
                            ("curation_completed", "Curation Completed"),
                            ("locked", "Locked"),
                            ("unlocked", "Unlocked"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        help_text="The status of the case.",
                    ),
                ),
                (
                    "event_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the event actually occurred. May differ from timestamp for retrospective entries.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        db_column="case_orcabus_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.case",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="archive_by_user_orcabus_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archived_states",
                        to="app.user",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by_user_orcabus_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_states",
                        to="app.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalCaseUserLink",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Some description of the user in the case (e.g. 'Case Owner', 'Case Manager', etc.)",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, editable=False)),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_column="case_orcabus_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="app.case",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.historicalcase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_orcabus_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="app.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalCaseUserLink",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "orcabus_id",
                    app.fields.OrcaBusIdField(primary_key=True, serialize=False),
                ),
                ("text", models.CharField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_column="case_orcabus_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.case",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        db_column="state_orcabus_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.state",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="archived_by_user_orcabus_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archived_comments",
                        to="app.user",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by_user_orcabus_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_comments",
                        to="app.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaseUserLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Some description of the user in the case (e.g. 'Case Owner', 'Case Manager', etc.)",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        db_column="case_orcabus_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.case",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_orcabus_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("case", "user")},
            },
        ),
        migrations.AddField(
            model_name="case",
            name="user_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="case_set",
                through="app.CaseUserLink",
                to="app.user",
            ),
        ),
    ]
