# Generated by Django 5.2.2 on 2026-04-13 04:51

import app.fields
import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "orcabus_id",
                    app.fields.OrcaBusIdField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, null=True, unique=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="A brief description of the case",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("wgts", "WGTS"), ("cttso", "ctTSO")],
                        help_text="The type for this case e.g. WGTS, ctTSO",
                        null=True,
                    ),
                ),
                (
                    "study_type",
                    models.CharField(
                        choices=[("clinical", "Clinical"), ("research", "Research")],
                        help_text='Whether this is a "clinical" or "research" case',
                        null=True,
                    ),
                ),
                (
                    "creation_mode",
                    models.CharField(
                        choices=[
                            ("autogenerated", "Auto-generated"),
                            ("edited", "Edited"),
                            ("manual", "Manual"),
                        ],
                        help_text="Creation mode: autogenerated by the system, reviewed/edited by a user, or manually created",
                    ),
                ),
                (
                    "is_report_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether a report is required for this case",
                    ),
                ),
                (
                    "is_nata_accredited",
                    models.BooleanField(
                        default=True,
                        help_text="Whether a case is a NATA accredited case",
                    ),
                ),
                (
                    "trello_url",
                    models.URLField(
                        blank=True, help_text="The URL to the Trello board", null=True
                    ),
                ),
                (
                    "alias",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of aliases for this case, typically populated with external IDs to make searching easier.",
                        null=True,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExternalEntity",
            fields=[
                (
                    "orcabus_id",
                    app.fields.OrcaBusIdField(primary_key=True, serialize=False),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        help_text="The prefix in the orcabus_id, indicating the entity's type or source system. Used to distinguish between different entity types or services.",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="The entity type within its service, e.g., 'library', 'subject', or 'sequence'. Typically matches the subpath or resource type in the source service.",
                        null=True,
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the microservice or domain where the entity is managed, e.g., 'metadata', 'workflow', or 'sequence'.",
                        null=True,
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        help_text="A human-friendly identifier for this entity, such as a library ID or workflow run ID, for easier recognition than the orcabus_id.",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalCase",
            fields=[
                ("orcabus_id", app.fields.OrcaBusIdField(db_index=True)),
                ("title", models.CharField(blank=True, db_index=True, null=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="A brief description of the case",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("wgts", "WGTS"), ("cttso", "ctTSO")],
                        help_text="The type for this case e.g. WGTS, ctTSO",
                        null=True,
                    ),
                ),
                (
                    "study_type",
                    models.CharField(
                        choices=[("clinical", "Clinical"), ("research", "Research")],
                        help_text='Whether this is a "clinical" or "research" case',
                        null=True,
                    ),
                ),
                (
                    "creation_mode",
                    models.CharField(
                        choices=[
                            ("autogenerated", "Auto-generated"),
                            ("edited", "Edited"),
                            ("manual", "Manual"),
                        ],
                        help_text="Creation mode: autogenerated by the system, reviewed/edited by a user, or manually created",
                    ),
                ),
                (
                    "is_report_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether a report is required for this case",
                    ),
                ),
                (
                    "is_nata_accredited",
                    models.BooleanField(
                        default=True,
                        help_text="Whether a case is a NATA accredited case",
                    ),
                ),
                (
                    "trello_url",
                    models.URLField(
                        blank=True, help_text="The URL to the Trello board", null=True
                    ),
                ),
                (
                    "alias",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of aliases for this case, typically populated with external IDs to make searching easier.",
                        null=True,
                    ),
                ),
                ("last_modified", models.DateTimeField(blank=True, editable=False)),
                ("history_user_id", models.CharField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical case",
                "verbose_name_plural": "historical cases",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "orcabus_id",
                    app.fields.OrcaBusIdField(primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaseExternalEntityLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_via",
                    models.CharField(
                        blank=True,
                        help_text="The external entity id that was added to the case",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        db_column="case_orcabus_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.case",
                    ),
                ),
                (
                    "external_entity",
                    models.ForeignKey(
                        db_column="external_entity_orcabus_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.externalentity",
                    ),
                ),
            ],
            options={
                "unique_together": {("case", "external_entity")},
            },
        ),
        migrations.AddField(
            model_name="case",
            name="external_entity_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="case_set",
                through="app.CaseExternalEntityLink",
                to="app.externalentity",
            ),
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "orcabus_id",
                    app.fields.OrcaBusIdField(primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("request_received", "Request Received"),
                            ("sample_received", "Sample Received"),
                            ("library_prep_started", "Library Preparation Started"),
                            ("library_qc_failed", "Library QC Failed"),
                            ("library_qc_requeue", "Library QC Re-queued"),
                            ("sequencing_started", "Sequencing Started"),
                            ("sequencing_complete", "Sequencing Complete"),
                            ("analysis_started", "Analysis Started"),
                            ("analysis_complete", "Analysis Complete"),
                            ("ready_for_curation", "Ready for Curation"),
                            ("curation_started", "Curation Started"),
                            ("curation_complete", "Curation Complete"),
                            ("locked_for_reporting", "Locked for Reporting"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        help_text="The status of the case.",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        db_column="case_orcabus_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.case",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "orcabus_id",
                    app.fields.OrcaBusIdField(primary_key=True, serialize=False),
                ),
                ("text", models.CharField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        db_column="case_orcabus_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.case",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        db_column="state_orcabus_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.state",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_orcabus_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaseUserLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Some description of the user in the case (e.g. 'Case Owner', 'Case Manager', etc.)",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        db_column="case_orcabus_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.case",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_orcabus_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("case", "user")},
            },
        ),
        migrations.AddField(
            model_name="case",
            name="user_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="case_set",
                through="app.CaseUserLink",
                to="app.user",
            ),
        ),
    ]
