# Generated by Django 5.2.2 on 2025-09-10 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="caseexternalentitylink",
            unique_together={("case", "external_entity")},
        ),
        migrations.AlterUniqueTogether(
            name="caseuserlink",
            unique_together={("case", "user")},
        ),
    ]
