# Generated by Django 6.0.4 on 2026-05-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_service", models.CharField(choices=[("redcap", "REDCap")])),
                (
                    "imported_at",
                    models.DateTimeField(
                        help_text="The timestamp of the last successful sync with the external service. This is used as the starting point for the next sync."
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="case",
            name="type",
            field=models.CharField(
                choices=[
                    ("wgts", "WGTS_T-N"),
                    ("cttso", "ctTSO500"),
                    ("wgs_n", "WGS_N"),
                ],
                help_text="The type for this case e.g. WGTS, ctTSO, WGS_N",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="type",
            field=models.CharField(
                choices=[
                    ("wgts", "WGTS_T-N"),
                    ("cttso", "ctTSO500"),
                    ("wgs_n", "WGS_N"),
                ],
                help_text="The type for this case e.g. WGTS, ctTSO, WGS_N",
            ),
        ),
    ]
