# Generated by Django 5.2.2 on 2026-01-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_caseexternalentitylink_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="creation_status",
            field=models.CharField(
                choices=[
                    ("autogenerated", "auto-generated"),
                    ("verified", "Verified"),
                    ("manual", "Manual"),
                ],
                default="autogenerated",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="case",
            name="trello_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
