# Generated by Django 6.0.4 on 2026-06-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_externalsynclog_alter_case_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="type",
            field=models.CharField(
                choices=[
                    ("wgts", "WGTS_T-N"),
                    ("cttso", "ctTSO500"),
                    ("wgs_n", "WGS_N"),
                ],
                help_text="The type for this case. One of: wgts, cttso, wgs_n",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="type",
            field=models.CharField(
                choices=[
                    ("wgts", "WGTS_T-N"),
                    ("cttso", "ctTSO500"),
                    ("wgs_n", "WGS_N"),
                ],
                help_text="The type for this case. One of: wgts, cttso, wgs_n",
            ),
        ),
    ]
