# Generated by Django 6.0.4 on 2026-06-19 08:57

import app.fields
import app.models.case
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_case_type_alter_historicalcase_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="redcap_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Snapshot of the latest raw REDCap payload received for this case. Not all REDCap fields are mapped to structured Django fields — this preserves the full source data for audit and UI rendering of REDCap information.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcase",
            name="redcap_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Snapshot of the latest raw REDCap payload received for this case. Not all REDCap fields are mapped to structured Django fields — this preserves the full source data for audit and UI rendering of REDCap information.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="alias",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of alternative identifiers for this case (e.g. external system IDs). Populated to make searching and cross-referencing easier.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="A brief human-readable description of the case.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="is_nata_accredited",
            field=models.BooleanField(
                default=True,
                help_text="Whether this case is processed under NATA accreditation.",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="is_report_required",
            field=models.BooleanField(
                default=True,
                help_text="Whether a formal report must be produced for this case.",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="links",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Named external URLs related to this case, e.g. {"trello": "https://...", "drive": "https://..."}',
                null=True,
                validators=[app.models.case.validate_urls_dict],
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="request_form_id",
            field=models.CharField(
                help_text="Unique identifier from the external request form that originated this case. Used as the correlation key when linking external entities that arrive asynchronously.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="study_type",
            field=models.CharField(
                choices=[("clinical", "Clinical"), ("research", "Research")],
                help_text='Whether this is a "clinical" or "research" case.',
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="type",
            field=models.CharField(
                choices=[
                    ("wgts", "WGTS_T-N"),
                    ("cttso", "ctTSO500"),
                    ("wgs_n", "WGS_N"),
                ],
                help_text="Workflow/assay type for this case. One of: wgts, cttso, wgs_n",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="alias",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of alternative identifiers for this case (e.g. external system IDs). Populated to make searching and cross-referencing easier.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="A brief human-readable description of the case.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="is_nata_accredited",
            field=models.BooleanField(
                default=True,
                help_text="Whether this case is processed under NATA accreditation.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="is_report_required",
            field=models.BooleanField(
                default=True,
                help_text="Whether a formal report must be produced for this case.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="links",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Named external URLs related to this case, e.g. {"trello": "https://...", "drive": "https://..."}',
                null=True,
                validators=[app.models.case.validate_urls_dict],
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="request_form_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique identifier from the external request form that originated this case. Used as the correlation key when linking external entities that arrive asynchronously.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="study_type",
            field=models.CharField(
                choices=[("clinical", "Clinical"), ("research", "Research")],
                help_text='Whether this is a "clinical" or "research" case.',
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="type",
            field=models.CharField(
                choices=[
                    ("wgts", "WGTS_T-N"),
                    ("cttso", "ctTSO500"),
                    ("wgs_n", "WGS_N"),
                ],
                help_text="Workflow/assay type for this case. One of: wgts, cttso, wgs_n",
            ),
        ),
        migrations.CreateModel(
            name="PendingExternalEntity",
            fields=[
                (
                    "orcabus_id",
                    app.fields.OrcaBusIdField(
                        help_text="Internal record ID for this pending entity entry.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable identifier sourced from the REDCap payload that is expected to map one-to-one with the orcabus_id once the entity is created by the originating microservice (e.g. a library ID such as 'LIB_001'). Corresponds to ExternalEntity.alias after resolution.",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="The entity type within its originating service, e.g., 'library', 'sample', or 'workflowrun'. Typically matches the resource type or subpath in the source service API.",
                        null=True,
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the microservice or domain expected to create this entity, e.g., 'metadata', 'workflow', or 'sequence'.",
                        null=True,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        db_column="case_orcabus_id",
                        help_text="The case this pending external entity is associated with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_external_entities",
                        to="app.case",
                    ),
                ),
            ],
            options={
                "unique_together": {("alias", "type", "service_name")},
            },
        ),
    ]
