# Generated by Django 5.2.2 on 2026-01-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_case_creation_status_case_trello_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="alias",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
