# Generated by Django 6.0.7 on 2026-07-27 23:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    State = apps.get_model("app", "State")
    db_alias = schema_editor.connection.alias

    # This status will be deleted, and re-populated from REDCap import service sync.
    to_delete = State.objects.using(db_alias).filter(
        status__in=["sample_received", "request_received"]
    )
    to_delete.delete()


def reverse_func(apps, schema_editor):
    # There's no way to know what was deleted, so this can't restore rows.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_case_type_alter_historicalcase_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="state",
            name="event_at",
        ),
        migrations.AddField(
            model_name="case",
            name="due_date",
            field=models.DateField(
                blank=True, help_text="The due date for the report.", null=True
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="study_id",
            field=models.CharField(
                blank=True,
                help_text="[REDCap-managed] The study_id within the defined study_name as recorded in REDCap.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="study_name",
            field=models.CharField(
                blank=True,
                help_text="[REDCap-managed] The study_name for this case as recorded in REDCap.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="ur_number",
            field=models.CharField(
                blank=True,
                help_text="[REDCap-managed] The UR (Unit Record) number for this case, as recorded in REDCap.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcase",
            name="due_date",
            field=models.DateField(
                blank=True, help_text="The due date for the report.", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalcase",
            name="study_id",
            field=models.CharField(
                blank=True,
                help_text="[REDCap-managed] The study_id within the defined study_name as recorded in REDCap.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcase",
            name="study_name",
            field=models.CharField(
                blank=True,
                help_text="[REDCap-managed] The study_name for this case as recorded in REDCap.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcase",
            name="ur_number",
            field=models.CharField(
                blank=True,
                help_text="[REDCap-managed] The UR (Unit Record) number for this case, as recorded in REDCap.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="state",
            name="event_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="When the event actually occurred. May differ from created_at for retrospective entries.",
            ),
        ),
        migrations.AddField(
            model_name="state",
            name="event_time",
            field=models.TimeField(
                blank=True,
                help_text="When the event time actually occurred. May differ from created_at for retrospective entries.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="request_form_id",
            field=models.CharField(
                help_text="[REDCap-managed] The unique ID from REDCap ('request_id') associated with this case.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="type",
            field=models.CharField(
                choices=[
                    ("wgts", "WGTS_T-N"),
                    ("cttso", "ctTSO500"),
                    ("wgs_n", "WGS_N"),
                ],
                help_text="[REDCap-managed] The type for this case, mapped from REDCap 'rf_test_requested'. One of: wgts, cttso, wgs_n",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="request_form_id",
            field=models.CharField(
                db_index=True,
                help_text="[REDCap-managed] The unique ID from REDCap ('request_id') associated with this case.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="type",
            field=models.CharField(
                choices=[
                    ("wgts", "WGTS_T-N"),
                    ("cttso", "ctTSO500"),
                    ("wgs_n", "WGS_N"),
                ],
                help_text="[REDCap-managed] The type for this case, mapped from REDCap 'rf_test_requested'. One of: wgts, cttso, wgs_n",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                db_column="archived_by_user_orcabus_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="archived_states",
                to="app.user",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="status",
            field=models.CharField(
                choices=[
                    ("request_received", "Request Received"),
                    ("wgts_tumour_sample_received", "WGTS Tumour Sample Received"),
                    ("wgts_germline_sample_received", "WGTS Germline Sample Received"),
                    ("cttso_sample_received", "CTTSO Sample Received"),
                    ("all_sample_received", "All Sample Received"),
                    ("library_partially_failed", "Library Partially Failed"),
                    ("sequencing_started", "Sequencing Started"),
                    ("sequencing_completed", "Sequencing Completed"),
                    ("bioinformatics_started", "Bioinformatics Started"),
                    ("bioinformatics_completed", "Bioinformatics Completed"),
                    ("curation_started", "Curation Started"),
                    ("curation_completed", "Curation Completed"),
                    ("locked", "Locked"),
                    ("unlocked", "Unlocked"),
                    ("failed", "Failed"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                ],
                help_text="The status of the case.",
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
