# Generated by Django 6.0.4 on 2026-08-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_case_redcap_payload_historicalcase_redcap_payload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="rnasum_references",
            field=models.JSONField(
                blank=True,
                help_text="[REDCap-managed] Reference dataset(s) selected for RNAsum analysis. Only the selected values from the REDCap multi-value checkbox are recorded here as a list of strings.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcase",
            name="rnasum_references",
            field=models.JSONField(
                blank=True,
                help_text="[REDCap-managed] Reference dataset(s) selected for RNAsum analysis. Only the selected values from the REDCap multi-value checkbox are recorded here as a list of strings.",
                null=True,
            ),
        ),
    ]
