# Generated by Django 6.0.4 on 2026-08-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_case_rnasum_references_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="rnasum_references",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[REDCap-managed] Reference dataset(s) selected for RNAsum analysis. Only the selected values from the REDCap multi-value checkbox are recorded here as a list of strings.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="rnasum_references",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[REDCap-managed] Reference dataset(s) selected for RNAsum analysis. Only the selected values from the REDCap multi-value checkbox are recorded here as a list of strings.",
                null=True,
            ),
        ),
    ]
