# generated by datamodel-codegen:
#   filename:  CaseRelationshipUpdate.schema.json
#   timestamp: 2026-08-13T09:00:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field


class Source(Enum):
    orcabus_casemanager = "orcabus.casemanager"


class Action(Enum):
    CREATE = "CREATE"
    DELETE = "DELETE"


class CaseRelationshipUpdate(BaseModel):
    action: Action
    addedVia: str
    case: dict[str, Any]
    externalEntity: dict[str, Any]


class CaseRelationshipUpdateEvent(BaseModel):
    id: str | None = None
    region: str | None = None
    resources: list[str] | None = None
    source: Source
    time: AwareDatetime | None = None
    version: str | None = None
    account: str | None = None
    detail_type: str = Field(..., alias="detail-type")
    detail: CaseRelationshipUpdate
