import os
from typing import List

import psycopg
import textwrap

from app.models import Case, CaseExternalEntityLink, ExternalEntity
from app.service.utils import get_ro_orcabus_secret

ro_secret = get_ro_orcabus_secret()
db_host = ro_secret.get("host", "localhost")
db_port = ro_secret.get("port", "5432")
db_user = ro_secret.get("username", "orcabus")
db_password = ro_secret.get("password", "orcabus")


class CttsoPgsql:

    def __init__(self):
        self.mm_conn = psycopg.connect(
            f"host={db_host} port={db_port} dbname=metadata_manager user={db_user} password={db_password}"
        )
        self.mm_cur = self.mm_conn.cursor()

        self.wfm_conn = psycopg.connect(
            f"host={db_host} port={db_port} dbname=workflow_manager user={db_user} password={db_password}"
        )
        self.wfm_cur = self.wfm_conn.cursor()

    def set_mm_cursor(self):
        sql_statement = textwrap.dedent(
            f"""
            SELECT orcabus_id, library_id
            FROM app_library
            WHERE phenotype='tumor' AND type='ctDNA' AND regexp_like(library_id, '^\\D+(?:24|25).*$')
            ORDER BY orcabus_id ASC;
        """
        ).strip()
        self.mm_cur.execute(sql_statement)

    def get_mm_cursor_results(self):
        return self.mm_cur.fetchmany(100)

    def set_wfr_cursor(self, library_orcabus_id: List[str]):
        sql_statement = textwrap.dedent(
            f"""
            SELECT
                wf_lib_assn.library_id as library_orcabus_id,
                wf_run.orcabus_id as workflow_run_orcabus_id,
                wf_run.portal_run_id as portal_run_id
            FROM (
                workflow_manager_workflowrun AS wf_run
                INNER JOIN workflow_manager_workflow AS workflow
                    ON wf_run.workflow_id = workflow.orcabus_id
                INNER JOIN workflow_manager_libraryassociation AS wf_lib_assn
                    ON wf_run.orcabus_id = wf_lib_assn.workflow_run_id
            )
            WHERE
                wf_lib_assn.library_id IN ({",".join([f"""'{i}'""" for i in library_orcabus_id])})
                AND workflow.name IN (
                    'dragen-tso500-ctdna',
                    'pieriandx-tso500-ctdna',
                    'cttsov2',
                    'pieriandx'
                )
            ORDER BY wf_lib_assn.library_id DESC;
        """
        ).strip()
        self.wfm_cur.execute(sql_statement)

    def get_wfr_cursor_results(self):
        return self.wfm_cur.fetchall()

    def end(self):
        self.mm_cur.close()
        self.mm_conn.close()
        self.wfm_cur.close()
        self.wfm_conn.close()


def cttso_case_builder():
    pgsql = CttsoPgsql()

    pgsql.set_mm_cursor()
    library_set = pgsql.get_mm_cursor_results()

    while library_set:
        libraries_case_dict = {}

        for orc_id, lib_id in library_set:
            case, is_new = Case.objects.get_or_create(
                external_entity_set__orcabus_id=orc_id,
                defaults={
                    "title": f"cttso-{lib_id}",
                    "creation_status": "autogenerated",
                },
            )

            if is_new:
                libraries_case_dict[orc_id] = case

                lib_entity, _ = ExternalEntity.objects.get_or_create(
                    orcabus_id=orc_id,
                    defaults={
                        "prefix": "lib",
                        "type": "library",
                        "service_name": "metadata",
                        "alias": lib_id,
                    },
                )
                CaseExternalEntityLink.objects.get_or_create(
                    case=case, external_entity=lib_entity
                )
        library_set = pgsql.get_mm_cursor_results()

        if not libraries_case_dict.keys():
            continue
        pgsql.set_wfr_cursor(list(libraries_case_dict.keys()))
        workflow_runs = pgsql.get_wfr_cursor_results()

        for library_orcabus_id, wf_run_orcabus_id, portal_run_id in workflow_runs:
            wfr_entity, _ = ExternalEntity.objects.get_or_create(
                orcabus_id=wf_run_orcabus_id,
                defaults={
                    "prefix": "wfr",
                    "type": "workflow_run",
                    "service_name": "workflow",
                    "alias": portal_run_id,
                },
            )
            case = libraries_case_dict[library_orcabus_id]
            CaseExternalEntityLink.objects.get_or_create(
                case=case, external_entity=wfr_entity
            )

    pgsql.end()


class WgtsPgsql:

    def __init__(self):
        self.mm_conn = psycopg.connect(
            f"host={db_host} port={db_port} dbname=metadata_manager user={db_user} password={db_password}"
        )
        self.mm_cur = self.mm_conn.cursor()

        self.wfm_conn = psycopg.connect(
            f"host={db_host} port={db_port} dbname=workflow_manager user={db_user} password={db_password}"
        )
        self.wfm_cur = self.wfm_conn.cursor()

    def set_mm_cursor(self):
        sql_statement = textwrap.dedent(
            f"""
            SELECT orcabus_id, library_id
            FROM app_library
            WHERE phenotype='tumor' AND type='WGS' AND regexp_like(library_id, '^\\D+(?:24|25).*$')
            ORDER BY orcabus_id ASC;
        """
        ).strip()
        self.mm_cur.execute(sql_statement)

    def get_mm_cursor_results(self):
        return self.mm_cur.fetchmany(100)

    def set_wfr_cursor(self, library_orcabus_id: List[str]):
        sql_statement = textwrap.dedent(
            f"""
            SELECT DISTINCT
                wf_lib_assn.library_id as library_orcabus_id,
                wf_lib.library_id as library_id_alias,
                wf_run.orcabus_id as workflow_run_orcabus_id,
                wf_run.portal_run_id as portal_run_id,
                wf_lib_assn.library_id IN ({",".join([f"""'{i}'""" for i in library_orcabus_id])}) as is_tumor_library
            FROM (
                workflow_manager_workflowrun AS wf_run
                INNER JOIN workflow_manager_workflow AS workflow
                    ON wf_run.workflow_id = workflow.orcabus_id
                INNER JOIN workflow_manager_libraryassociation AS wf_lib_assn
                    ON wf_run.orcabus_id = wf_lib_assn.workflow_run_id
                INNER JOIN workflow_manager_library AS wf_lib
                    ON wf_lib_assn.library_id = wf_lib.orcabus_id
                INNER JOIN workflow_manager_libraryassociation AS wf_filter
				    ON wf_run.orcabus_id = wf_filter.workflow_run_id
                    AND wf_filter.library_id IN ({",".join([f"""'{i}'""" for i in library_orcabus_id])})
            )
            WHERE
                workflow.name IN (
                    'oncoanalyser-wgts-dna-rna',
                    'rnasum',
                    'umccrise',
                    'tumor-normal',
                    'oncoanalyser-wgts-dna',
                    'dragen-wgts-dna',
                    'sash',
                    'wts',
                    'dragen-wgts-rna'
                )
            ORDER BY is_tumor_library DESC;
        """
        ).strip()
        self.wfm_cur.execute(sql_statement)

    def get_wfr_cursor_results(self):
        return self.wfm_cur.fetchall()

    def end(self):
        self.mm_cur.close()
        self.mm_conn.close()
        self.wfm_cur.close()
        self.wfm_conn.close()


def wgts_case_builder():
    pgsql = WgtsPgsql()

    pgsql.set_mm_cursor()
    library_set = pgsql.get_mm_cursor_results()

    while library_set:

        libraries_case_dict = {}

        for orc_id, lib_id in library_set:
            case, is_new = Case.objects.get_or_create(
                external_entity_set__orcabus_id=orc_id,
                defaults={
                    "title": f"wgts-{lib_id}",
                    "creation_status": "autogenerated",
                },
            )

            if is_new:
                libraries_case_dict[orc_id] = case

                lib_entity, _ = ExternalEntity.objects.get_or_create(
                    orcabus_id=orc_id,
                    defaults={
                        "prefix": "lib",
                        "type": "library",
                        "service_name": "metadata",
                        "alias": lib_id,
                    },
                )
                CaseExternalEntityLink.objects.get_or_create(
                    case=case, external_entity=lib_entity
                )
        library_set = pgsql.get_mm_cursor_results()

        if not libraries_case_dict.keys():
            continue
        pgsql.set_wfr_cursor(list(libraries_case_dict.keys()))
        workflow_runs = pgsql.get_wfr_cursor_results()
        # the following dict is just
        workflow_runs_case_dict = {}
        for (
            library_orcabus_id,
            library_id,
            wf_run_orcabus_id,
            portal_run_id,
            is_tumor_lib,
        ) in workflow_runs:

            if is_tumor_lib:
                # The result will be descending so the first match is the tumor library
                wfr_entity, _ = ExternalEntity.objects.get_or_create(
                    orcabus_id=wf_run_orcabus_id,
                    defaults={
                        "prefix": "wfr",
                        "type": "workflow_run",
                        "service_name": "workflow",
                        "alias": portal_run_id,
                    },
                )
                case = libraries_case_dict[library_orcabus_id]
                CaseExternalEntityLink.objects.get_or_create(
                    case=case, external_entity=wfr_entity
                )
                # this will be used to link the normal library later
                workflow_runs_case_dict[wf_run_orcabus_id] = case
            else:
                lib_entity, is_lib_entity_new = ExternalEntity.objects.get_or_create(
                    orcabus_id=library_orcabus_id,
                    defaults={
                        "prefix": "lib",
                        "type": "library",
                        "service_name": "metadata",
                        "alias": library_id,
                    },
                )
                if is_lib_entity_new:
                    # using the link from the wf_run_orcabus_id that has been previous linked
                    case = workflow_runs_case_dict[wf_run_orcabus_id]
                    CaseExternalEntityLink.objects.get_or_create(
                        case=case, external_entity=lib_entity
                    )
    pgsql.end()
