import json
import logging
from functools import partial
from typing import Literal, Any, List, TypedDict, cast

from django.db import transaction
from django.db.models.functions import Coalesce

from app.aws.event_bridge import emit_event
from app.models import (
    Case,
    CaseExternalEntityLink,
    ExternalEntity,
    PendingExternalEntity,
    State,
    Comment,
    CaseUserLink,
)
from app.schemas.events.CaseRelationshipStateChange.case_relationship_state_change_model import (
    CaseRelationshipStateChange,
    Action,
    DetailType,
)
from app.schemas.events.WorkflowRunUpdate.workflow_run_update_model import (
    WorkflowRunUpdate,
)
from app.serializers.case import (
    CaseHistorySerializer,
    CaseUserLinkSerializer,
    CaseExternalEntityLinkSerializer,
    CaseSerializer,
)
from app.serializers.external_entity import ExternalEntitySerializer
from app.service.draft_builder import build_cttso_workflow_run_draft
from app.service.external_entity import (
    get_case_library_entities,
    get_case_workflow_runs_by_name,
)

logger = logging.getLogger(__name__)

# The real workflow name of cttso
CTTSO_WORKFLOW_NAME = "dragen-tso500-ctdna"


@transaction.atomic
def link_case_to_external_entity_and_emit(
    case: Case, external_entity: ExternalEntity, history_user: str | None
) -> CaseExternalEntityLink:
    """
    Save the case-external entity relationship and emit an event to the Event Bridge.
    """

    case_entity_link = CaseExternalEntityLink(
        case=case, external_entity=external_entity
    )
    if history_user:
        case_entity_link._history_user = history_user
    case_entity_link.save()

    case_data = dict(CaseSerializer(case_entity_link.case).data)
    external_entity_data = dict(
        ExternalEntitySerializer(case_entity_link.external_entity).data
    )

    relationship_change_event = CaseRelationshipStateChange(
        action=Action.CREATE,
        refId=str(case_entity_link.pk),
        timestamp=case_entity_link.timestamp.isoformat(),
        case=case_data,
        externalEntity=external_entity_data,
    )

    # emit event to Event Bridge only after the transaction commits successfully
    transaction.on_commit(
        partial(
            emit_event,
            detail_type=DetailType.CaseRelationshipStateChange.value,
            event_detail_model=relationship_change_event,
        )
    )

    return case_entity_link


@transaction.atomic
def unlink_case_to_external_entity_and_emit(
    case_external_entity: CaseExternalEntityLink, history_user: str | None
) -> CaseExternalEntityLink:
    """
    Remove the case-external entity relationship and emit an event to the Event Bridge.
    """
    # Serialize before deletion so the data is still accessible
    case_data = dict(CaseSerializer(case_external_entity.case).data)
    external_entity_data = dict(
        ExternalEntitySerializer(case_external_entity.external_entity).data
    )
    link_id = str(case_external_entity.pk)
    timestamp = case_external_entity.timestamp.isoformat()

    if history_user:
        case_external_entity._history_user = history_user
    case_external_entity.delete()

    relationship_change_event = CaseRelationshipStateChange(
        action=Action.DELETE,
        refId=link_id,
        timestamp=timestamp,
        case=case_data,
        externalEntity=external_entity_data,
    )
    # emit event to Event Bridge only after the transaction commits successfully
    transaction.on_commit(
        partial(
            emit_event,
            detail_type=DetailType.CaseRelationshipStateChange.value,
            event_detail_model=relationship_change_event,
        )
    )
    return case_external_entity


EventAction = Literal["created", "updated", "deleted", "archived"]
ModelType = Literal[
    "case", "state", "comment", "case_user_link", "case_external_entity_link"
]


class CaseHistoryEntry(TypedDict):
    """
    A single entry in a case's audit/history timeline.
    Returned as a time-sorted list by get_case_history().
    """

    timestamp: str  # ISO datetime of when the event occurred
    event_type: EventAction  # the action performed: create, update, or delete
    model_type: ModelType  # which model was affected: case, state, or comment
    actor: str | None  # user who triggered it (email); None if system
    description: str  # human-readable one-liner summary
    detail: dict[str, Any] | None


def get_case_activity(case: Case) -> list:
    """
    Will generate a view of changes happening on a case.

    Since this is generated by combining
    """
    entries: list[CaseHistoryEntry] = []

    # --- Case field changes ---
    for h in case.history.all():
        if h.history_type == "~":
            old_record = h.prev_record
            delta = h.diff_against(old_record)
            description = (
                "; ".join(
                    f"'{change.field}' changed from '{change.old}' to '{change.new}'"
                    for change in delta.changes
                )
                or "Case updated"
            )
        elif h.history_type == "+":
            description = "Case created"
        else:
            description = "Case deleted"
        entries.append(
            {
                "timestamp": h.history_date.isoformat(),
                "event_type": (
                    "created"
                    if h.history_type == "+"
                    else "deleted" if h.history_type == "-" else "updated"
                ),
                "model_type": "case",
                "actor": str(h.history_user_id) if h.history_user_id else None,
                "description": description,
                "detail": CaseHistorySerializer(h).data,
            }
        )

    # --- Case User Link changes ---
    for h in CaseUserLink.history.filter(case=case).select_related("user").all():
        event_type: EventAction = (
            "created"
            if h.history_type == "+"
            else "deleted" if h.history_type == "-" else "updated"
        )

        entries.append(
            {
                "timestamp": h.history_date.isoformat(),
                "event_type": event_type,
                "model_type": "case_user_link",
                "actor": str(h.history_user_id) if h.history_user_id else None,
                "description": f""""{h.user.email}" {"linked" if h.history_type == "+" else "unlinked"}",""",
                "detail": CaseUserLinkSerializer(h).data,
            }
        )

    # --- Case External Entity Link changes ---
    for h in (
        CaseExternalEntityLink.history.filter(case=case)
        .select_related("external_entity")
        .all()
    ):
        event_type: EventAction = (
            "created"
            if h.history_type == "+"
            else "deleted" if h.history_type == "-" else "updated"
        )
        entries.append(
            {
                "timestamp": h.history_date.isoformat(),
                "event_type": event_type,
                "model_type": "case_external_entity_link",
                "actor": str(h.history_user_id) if h.history_user_id else None,
                "description": f""""{h.external_entity.alias}" {"linked" if h.history_type == "+" else "unlinked"}""",
                "detail": CaseExternalEntityLinkSerializer(h).data,
            }
        )

    # --- States (append-only) ---
    for state in (
        State.objects.filter(case=case)
        .select_related("created_by", "archived_by")
        .annotate(last_changed=Coalesce("archived_at", "created_at"))
        .order_by("last_changed")
    ):
        entries.append(
            {
                "timestamp": (
                    state.archived_at.isoformat()
                    if state.is_archived
                    else state.created_at.isoformat()
                ),
                "event_type": "archived" if state.is_archived else "created",
                "model_type": "state",
                "actor": (
                    state.archived_by.email
                    if state.archived_by
                    else state.created_by.email
                ),
                "description": f"Status set to '{state.status}'",
                "detail": {
                    "orcabus_id": str(state.orcabus_id),
                    "status": state.status,
                    "created_at": state.created_at.isoformat(),
                    "created_by": state.created_by.email,
                    "is_archived": state.is_archived,
                    "archived_at": (
                        state.archived_at.isoformat() if state.archived_at else None
                    ),
                },
            }
        )

    # --- Comments (append-only) ---
    for comment in (
        Comment.objects.filter(case=case)
        .select_related("created_by", "archived_by")
        .annotate(last_changed=Coalesce("archived_at", "created_at"))
        .order_by("last_changed")
    ):
        entries.append(
            {
                "timestamp": (
                    comment.archived_at.isoformat()
                    if comment.archived_at
                    else comment.created_at.isoformat()
                ),
                "event_type": "archived" if comment.is_archived else "created",
                "model_type": "comment",
                "actor": (
                    comment.archived_by.email
                    if comment.archived_by
                    else comment.created_by.email
                ),
                "description": (
                    f"Comment: {comment.text[:80]}..."
                    if comment.text and len(comment.text) > 80
                    else comment.text
                ),
                "detail": {
                    "orcabus_id": str(comment.orcabus_id),
                    "text": comment.text,
                    "created_at": (
                        comment.created_at.isoformat() if comment.created_at else None
                    ),
                    "is_archived": comment.is_archived,
                    "archived_at": (
                        comment.archived_at.isoformat() if comment.archived_at else None
                    ),
                },
            }
        )

    return sorted(entries, key=lambda x: x["timestamp"], reverse=True)


@transaction.atomic
def publish_cttso_workflow_run_draft_for_case(case: Case) -> None:
    """
    Validate, build, and publish a WorkflowRunUpdate DRAFT event for a single case.

    MVP scope: only "cttso" cases are supported today, so the workflow is
    hardcoded for that case type. Other case types are intentionally skipped.

    Skips dispatching a workflow-run draft if:
    - case is not "cttso" type (initial implementation)
    - no library found within the case
    - a workflow_run whose actual workflow name is CTTSO_WORKFLOW_NAME has
      already been linked to the case

    The event is only emitted to EventBridge once the surrounding transaction
    commits successfully (see transaction.on_commit below).
    """
    if case.type != "cttso":
        logger.debug(f"Skipping case {case.orcabus_id}: type is {case.type}, not cttso")
        return

    logger.info(f"Processing cttso case: {case.orcabus_id}")

    # Check for workflow run deduplication, scoped to CTTSO_WORKFLOW_NAME only —
    # a case may have other, unrelated workflow_run links that should not block
    # a cttso draft.
    existing_cttso_workflow_runs = get_case_workflow_runs_by_name(
        case, CTTSO_WORKFLOW_NAME
    )
    if existing_cttso_workflow_runs:
        logger.warning(
            f"Skipping case {case.orcabus_id}: {CTTSO_WORKFLOW_NAME} workflow "
            f"run(s) already exist: {json.dumps(existing_cttso_workflow_runs, indent=2)}"
        )
        return

    logger.info(
        f"No existing {CTTSO_WORKFLOW_NAME} workflow runs found for case {case.orcabus_id}"
    )

    # Retrieve library entities linked to the case (type="library", service_name="metadata")
    library_entities = get_case_library_entities(case)
    if not library_entities:
        logger.warning(f"Skipping case {case.orcabus_id}: no library entities found")
        return

    logger.info(
        f"Found {len(library_entities)} library entities for case {case.orcabus_id}"
    )

    # Validate each library entity has orcabus_id and alias
    for library_entity in library_entities:
        if not library_entity.orcabus_id:
            error_msg = f"Library entity missing orcabus_id: {library_entity}"
            logger.error(error_msg)
            raise ValueError(error_msg)
        if not library_entity.alias:
            error_msg = f"Library entity {library_entity.orcabus_id} missing alias"
            logger.error(error_msg)
            raise ValueError(error_msg)

    logger.info(
        f"All library entities validated for case {case.orcabus_id}: "
        f"{[lib.alias for lib in library_entities]}"
    )

    # Build workflow run draft payload using draft_builder module. This function
    # fetches workflow metadata and constructs minimal draft workflow-run payload.
    workflow_run_draft_dict = build_cttso_workflow_run_draft(case, library_entities)

    # Create Pydantic model instance from the payload
    workflow_run_draft_model = WorkflowRunUpdate(**workflow_run_draft_dict)
    portal_run_id = workflow_run_draft_model.portalRunId

    logger.info(
        f"Successfully built workflow run draft for case {case.orcabus_id}, "
        f"portal_run_id={portal_run_id}"
    )

    def _queue_pending_workflow_run_and_emit() -> None:
        """
        Post-commit: queue a PendingExternalEntity for this draft workflow run
        (keyed by portal_run_id, since the real wfr.* orcabus_id isn't assigned
        until the workflow service processes the draft), then emit the
        WorkflowRunUpdate event. handler/workflow_run_linking.py will later
        promote this to a real ExternalEntity + CaseExternalEntityLink once the
        workflow service assigns the real orcabus_id and emits the resulting
        WorkflowRunStateChange event.
        """
        _, created = PendingExternalEntity.objects.get_or_create(
            case=case,
            alias=portal_run_id,
            type="workflow_run",
            service_name="workflow",
        )
        logger.info(
            f"{'Queued' if created else 'Already queued'} PendingExternalEntity for "
            f"draft workflow run portal_run_id={portal_run_id} on case {case.orcabus_id}"
        )

        emit_event(
            detail_type="WorkflowRunUpdate",
            event_detail_model=workflow_run_draft_model,
        )

    # Queue the draft workflow run as a PendingExternalEntity and emit the
    # WorkflowRunUpdate (DRAFT) event only after the transaction commits successfully.
    transaction.on_commit(_queue_pending_workflow_run_and_emit)

    logger.info(
        f"Queued WorkflowRunUpdate event for case {case.orcabus_id}, "
        f"portal_run_id={portal_run_id} (will publish on transaction commit)"
    )
